# @package _global_
defaults:
  - _self_

openai_api_key:
model_name: DeepSeek-R1-Distill-Llama-70B
max_context_length: 16384
exllama: False

system_tag_start: "<｜begin▁of▁sentence｜><|start_header_id|>system<|end_header_id|>\n\n"
system_tag_end: "<|eot_id|>"

user_tag_start: "<|start_header_id|>user<|end_header_id|>\n\n"
user_tag_end: "<|eot_id|>"

ai_tag_start: "<|start_header_id|>assistant<|end_header_id|>\n\n"
ai_tag_end: "<|eot_id|>"

stop_words:
 - "<|eot_id|>"
 - "<｜end▁of▁sentence｜>"
 - "<|eom_id|>"